<a href="https://colab.research.google.com/github/Ayshan-M/Ayshan-M/blob/main/Reading_data_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reading Data

**Subtitle:** CDH Critical Intro to Python

**Author:** [PUT YOUR NAME HERE]

**Date:** February 9, 2026

---

## Goals

- Work with Jupyter notebooks in Python
- Read data of various types into Python
- Describe the sources of datasets
- Perform basic data exploration

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## 0: Opening this file

You'll download all of the lab files for this class as `.zip` files from Moodle. To use them, you'll have to unzip them into their own directory (not a temporary directory that lets you explore the files inside).

This is a Jupyter notebook (`.ipynb` file). Jupyter notebooks allow you to combine code, output, and text in one document. You can run code cells by selecting them and pressing `Shift + Enter` or clicking the "Run" button.

The notebook automatically has access to files and directories (folders) in the project directory. This makes it much easier to load multiple data sets.

If you get stuck on one of the questions below, first check the bottom of this document for hints. Then try googling your issue or talking to somebody sitting near you. Finally, raise your hand and I'll come help you out.

## 1: Rectangular data

The most common type of data we'll see is rectangular data, which is organized into a table of rows and columns. If data come to us in another form we'll often want to make them rectangular.

In the same directory as this notebook file, there's a directory called `data`. Inside, there's a comma-separated values (CSV) file called `seattle_airbnb.csv`. This contains data about 100 Airbnb listings from Seattle.

These data come from Inside Airbnb, http://insideairbnb.com/. Go to the website and have a look at the About, Behind, and Get the Data pages. *Use what you read to answer the questions below. Just type your answers below the questions.*

**Question 1.1: Who created these data sets?**

*[Murray Cox, the founder of Inside Airbnb.]*

**Question 1.2: Why did they do it?**

*[To make Airbnb's impact on housing and communities more transparent and support informed public discussion.]*

**Question 1.3: Where were the data sourced from?**

*[From publicly available information on the Airbnb website, including listings, calendars, and reviews.]*

## 2: Setup

Python doesn't come with everything we need loaded by default. Before we do anything else, we need to import *libraries* (also called packages or modules). Libraries contain specialized functions and data that we can use to do useful things. The main library we'll use is called **pandas**, which is the standard library for data manipulation, exploration, and analysis in Python.

You can read more about pandas here: https://pandas.pydata.org/

If a library hasn't been installed in your Python environment, you'll need to install it. For instance, you'd type `pip install pandas` in a terminal or command prompt. In Jupyter notebooks, you can also use `!pip install pandas`. You only need to do this once for each Python installation, but in order to use a library, you have to import it in each notebook or script.

Code cells let us incorporate code into notebooks like this one. They're very useful for creating interactive documents and for testing out new code. The output from a code cell shows up right below it. You can run a code cell by selecting it and pressing `Shift + Enter` or clicking the "Run" button.

**Question 2.1: Run this cell to import pandas and numpy (a numerical computing library):**

In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully!")

Libraries loaded successfully!

## 3: Importing data

To use data inside Python, we first have to import, or *read*, that data into our environment and save it to a variable.

In [11]:
airbnb_data = pd.read_csv("data/seattle_airbnb.csv")

When we do this, we assign the values of the data to a variable, `airbnb_data`, using the equals sign (`=`). The object we create is called a DataFrame (in pandas).

**Question 3.1: What is the role of each component in the above line of code?**

- `airbnb_data`: the variable name we used for the DataFrame
- `=`: *[assigns the value on the right to the variable on the left]*
- `pd.read_csv()`: *[read a CSV file into a pandas DataFrame]*
- `"data/seattle_airbnb.csv"`: *[the file path showing where the CSV file is located]*

## 4: Looking at the data

You can display the DataFrame by typing the name of the variable. In Jupyter notebooks, if a variable is the last line in a cell, it will automatically be displayed.

**Question 4.1: Run the cell below to display the DataFrame:**

In [12]:
airbnb_data

,id,name,neighbourhood_group,neighbourhood,price,number_of_reviews
0,2318,"Casa Madrona - Urban Oasis, 1 block from the P...",Central Area,Madrona,296,16
1,4291,Sunrise in Seattle Master Suite,Other neighborhoods,Roosevelt,82,54
2,5682,"Cozy Studio, min. to downtown -WiFi",Delridge,South Delridge,48,428
3,6606,"Fab, private seattle urban cottage!",Other neighborhoods,Wallingford,90,110
4,9419,Glorious sun room w/ memory foambed,Other neighborhoods,Georgetown,70,120
...,...,...,...,...,...,...
95,224763,"Location! Sleeps 4 WiFi Luxurious, Parking Inc!",Downtown,Belltown,149,72
96,225820,Family Friendly on Phinney Ridge,Other neighborhoods,Phinney Ridge,90,69
97,226495,"Fun apartment in Ballard, Seattle",Ballard,Whittier Heights,170,72
98,226536,Serene Room in Sunny Cottage near Discovery Park,Magnolia,Lawton Park,46,116
99,226677,Sunny Parisian beauty room w/ comfy bed,Other neighborhoods,Georgetown,55,101

The `.head()` method shows you the first five rows of a DataFrame by default.

**Question 4.3: Use the head method in the code cell below to show the first rows of airbnb_data:**

In [13]:
airbnb_data.head()

,id,name,neighbourhood_group,neighbourhood,price,number_of_reviews
0,2318,"Casa Madrona - Urban Oasis, 1 block from the P...",Central Area,Madrona,296,16
1,4291,Sunrise in Seattle Master Suite,Other neighborhoods,Roosevelt,82,54
2,5682,"Cozy Studio, min. to downtown -WiFi",Delridge,South Delridge,48,428
3,6606,"Fab, private seattle urban cottage!",Other neighborhoods,Wallingford,90,110
4,9419,Glorious sun room w/ memory foambed,Other neighborhoods,Georgetown,70,120

**Question 4.4: `.head()` shows the first 5 rows by default. Change the following code to show the first 10 rows:**

In [14]:
airbnb_data.head(10)

,id,name,neighbourhood_group,neighbourhood,price,number_of_reviews
0,2318,"Casa Madrona - Urban Oasis, 1 block from the P...",Central Area,Madrona,296,16
1,4291,Sunrise in Seattle Master Suite,Other neighborhoods,Roosevelt,82,54
2,5682,"Cozy Studio, min. to downtown -WiFi",Delridge,South Delridge,48,428
3,6606,"Fab, private seattle urban cottage!",Other neighborhoods,Wallingford,90,110
4,9419,Glorious sun room w/ memory foambed,Other neighborhoods,Georgetown,70,120
5,9460,Downtown/Convention Ctr B&B - Nice!,Downtown,First Hill,80,366
6,9531,The Adorable Sweet Orange Craftsman,West Seattle,Fairmount Park,165,34
7,9534,The Coolest Tangerine Dream MIL!,West Seattle,Fairmount Park,125,32
8,9596,"the down home , spacious, central and fab!",Other neighborhoods,Wallingford,120,61
9,9909,Luna Park Lower - West Seattle,West Seattle,Fairmount Park,125,48

What if you want to look at the *last* several rows of a DataFrame instead of the first several rows?

You can access help documentation for any function or method by typing `?` before it or using the `help()` function.

**Question 4.5: Based on what you know, show the last 5 rows of airbnb_data (hint: use `.tail()` instead of `.head()`)**

In [15]:
airbnb_data.tail()

,id,name,neighbourhood_group,neighbourhood,price,number_of_reviews
95,224763,"Location! Sleeps 4 WiFi Luxurious, Parking Inc!",Downtown,Belltown,149,72
96,225820,Family Friendly on Phinney Ridge,Other neighborhoods,Phinney Ridge,90,69
97,226495,"Fun apartment in Ballard, Seattle",Ballard,Whittier Heights,170,72
98,226536,Serene Room in Sunny Cottage near Discovery Park,Magnolia,Lawton Park,46,116
99,226677,Sunny Parisian beauty room w/ comfy bed,Other neighborhoods,Georgetown,55,101

You can extract a single column in several ways. The most common are:
- Using bracket notation: `dataframe['column_name']`
- Using dot notation: `dataframe.column_name` (only works if column name has no spaces)

**Question 4.6: Use bracket notation to display the 'price' column:**

In [16]:
airbnb_data['price']

0     296
1      82
2      48
3      90
4      70
     ...
95    149
96     90
97    170
98     46
99     55
Name: price, Length: 100, dtype: int64

**Question 4.7: Get basic information about the DataFrame using `.info()` and `.describe()` methods:**

In [18]:
airbnb_data.info()
airbnb_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   100 non-null    int64
 1   name                 100 non-null    object
 2   neighbourhood_group  100 non-null    object
 3   neighbourhood        100 non-null    object
 4   price                100 non-null    int64
 5   number_of_reviews    100 non-null    int64
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

                  id        price  number_of_reviews
count     100.000000   100.000000         100.000000
mean    98499.320000   213.940000         118.040000
std     77784.069268   921.470441         131.344402
min      2318.000000    40.000000           0.000000
25%     20927.750000    75.000000          35.000000
50%     79117.000000    97.500000          70.500000
75%    174081.000000   150.000000         132.250000
max    226677.000000  9300.000000         689.000000

In [19]:
airbnb_data.describe()

                  id        price  number_of_reviews
count     100.000000   100.000000         100.000000
mean    98499.320000   213.940000         118.040000
std     77784.069268   921.470441         131.344402
min      2318.000000    40.000000           0.000000
25%     20927.750000    75.000000          35.000000
50%     79117.000000    97.500000          70.500000
75%    174081.000000   150.000000         132.250000
max    226677.000000  9300.000000         689.000000

## 5: Hierarchical data

Data isn't always a single, flat table. Sometimes it's nested or hierarchical.

`colors.json` is a file in JSON format. This is a common format for web data. Python has a built-in `json` library for reading JSON files.

**Question 5.1: Run the code below to import the json library and read the file "data/colors.json":**

In [25]:
import json

with open("data/colors.json", "r") as f:
    colors_data = json.load(f)

print("JSON data loaded successfully!")

JSON data loaded successfully!

When you load JSON data, it becomes a Python dictionary (a data structure with keys and values):

In [26]:
print(type(json_data))
print(json_data)

<class 'dict'>
{'colors': [{'color': 'black', 'category': 'hue', 'type': 'primary', 'code': {'rgba': [255, 255, 255, 1], 'hex': '#000'}}, {'color': 'white', 'category': 'value', 'code': {'rgba': [0, 0, 0, 1], 'hex': '#FFF'}}, {'color': 'red', 'category': 'hue', 'type': 'primary', 'code': {'rgba': [255, 0, 0, 1], 'hex': '#FF0'}}, {'color': 'blue', 'category': 'hue', 'type': 'primary', 'code': {'rgba': [0, 0, 255, 1], 'hex': '#00F'}}, {'color': 'yellow', 'category': 'hue', 'type': 'primary', 'code': {'rgba': [255, 255, 0, 1], 'hex': '#FF0'}}, {'color': 'green', 'category': 'hue', 'type': 'secondary', 'code': {'rgba': [0, 255, 0, 1], 'hex': '#0F0'}}]}

You can use bracket notation `[]` to extract pieces of this data. For example, to get the 5th color (index 4, since Python uses 0-based indexing):

In [27]:
json_data['colors'][4]

{'color': 'yellow',
 'category': 'hue',
 'type': 'primary',
 'code': {'rgba': [255, 255, 0, 1], 'hex': '#FF0'}}

**Question 5.2: Display the information for the color red (hint: you'll need to try different indices):**

In [28]:
colors_data["colors"][2]

{'color': 'red',
 'category': 'hue',
 'type': 'primary',
 'code': {'rgba': [255, 0, 0, 1], 'hex': '#FF0'}}

## 6: Saving your work

Jupyter notebooks automatically save periodically, but you should also manually save using `Ctrl+S` (or `Cmd+S` on Mac) or by clicking the save icon.

**Question 6.1: Save your notebook now.**

You can also export your notebook in different formats (HTML, PDF, etc.) using the File menu → Download as.

You should save your work somewhere you can easily access it again, such as your cloud storage or local drive.

## Challenge: Excel worksheets

In the data folder, there is an Excel spreadsheet, `airbnb.xlsx`. It contains data for three cities (Seattle, Boston, Chicago) in separate sheets.

**Challenge:** Use pandas to read in all of this data. Read each sheet separately, then combine them into one DataFrame.

Hints:
- Look up `pd.read_excel()` documentation
- Use the `sheet_name` parameter to specify which sheet to read
- Use `pd.concat()` to combine multiple DataFrames

In [8]:
# Your code here
# You may need to install openpyxl: pip install openpyxl

## Just for fun: Image data

Images are data too, and Python can import and manipulate them as well. If you have extra time, check out the PIL/Pillow library:

https://pillow.readthedocs.io/en/stable/

In [9]:
# Uncomment to install and use:
# !pip install Pillow
# from PIL import Image
# import matplotlib.pyplot as plt

# cat = Image.open("data/Black_white_cat_on_fence.jpg")
# plt.imshow(cat)
# plt.axis('off')
# plt.show()

# # Flip the image
# cat_flipped = cat.transpose(Image.FLIP_TOP_BOTTOM)
# plt.imshow(cat_flipped)
# plt.axis('off')
# plt.show()

## Hints

**3.1**
- `=` is the assignment operator - it assigns the value on the right to the variable on the left
- `pd.read_csv()` is a pandas function that reads CSV files and returns a DataFrame
- `"data/seattle_airbnb.csv"` is the file path (location) of the data file

**4.3** You'll need to write: `airbnb_data.head()`

**4.4** You'll need to change the value from 5 to 10: `airbnb_data.head(10)`

**4.5** Use `.tail(5)` instead of `.head(5)`

**4.6** Use: `airbnb_data['price']`

**5.2** `json_data['colors'][4]` gave us the info for 'yellow', so try changing the 4 to other numbers to find 'red'. Remember Python uses 0-based indexing (starts counting at 0).